### ISSUE TITLE
NativeEthernet with long delay instruction or inside IntervalTimer loop function

### ISSUE THREAD

**Issue by tomotom** [vjmuzik/NativeEthernet#5]
Good afternoon,
I tried to use the NativeEthernet inside IntervalTimer function, however, after 1-2 minute(s), the NativeEthernet freezes for no appearent reason (it stops receiving packets, however the led on the magjack kit stills work and windows continues sending packets). When i move the NativeEthernet instructions inside the loop function, the NativeEthernet works perfectly (without freeze), except if there is a long delay instruction (as below ; if there is a long delay instruction, NativeEthernet also freezes ).
Below, there is a code that freezes.

Do you know how to solve it ?

Thank you

My Source code:

```
#include <NativeEthernet.h>
#include <NativeEthernetUdp.h>
EthernetUDP myUDP;
byte ip[] = {192, 168, 1, 177};
byte mac[] = {0x04, 0xE9, 0xE5, 0x00, 0x69, 0xEC};
#define NET_PORT 6450
uint8_t netPacket[1470];
unsigned short packetSize;
//IntervalTimer myTimerLoopNetwork;

void setup() {
  Ethernet.begin(mac,ip);
  myUDP.begin(NET_PORT);
//  Ethernet._fnet_poll.end(); // Note : poll is useless in my case and i wanted to know if it changes something or not (sadly it changes nothing)
//  myTimerLoopNetwork.begin(loopNetwork, 100);
}

void loop() {
  loopNetwork();
  delay(100);
}

//bool isLoopNetwork=false;
void loopNetwork(){
//  if(isLoopNetwork) return;
//  isLoopNetwork=true;
  packetSize = myUDP.parsePacket();
  if (packetSize){
//      isLoopNetwork=false;
      myUDP.read(netPacket, packetSize);
      Serial.print((char)(netPacket[0]));
      Serial.println(" test_for_freeze");
  }
//  isLoopNetwork=false;
}
```

**Comment by vjmuzik** [comment]
I didn't realize I wasn't receiving notifications for issues.

My best guess is that because you are only checking and reading one packet every 100ms you aren’t reading all the packets that could be in the buffer so eventually there is an overflow. There is nothing wrong with reading every 100ms, but you have to make sure you don't exceed the buffer in that timeframe and that you read everything that's there when you do since there may be more than one packet available. You should be able to easily accomplish that by encapsulating your if statement with a while loop like this so it will read all packets in the buffer.
```c++
//bool isLoopNetwork=false;
void loopNetwork(){
//  if(isLoopNetwork) return;
//  isLoopNetwork=true;
  while((packetSize = myUDP.parsePacket())){
    if (packetSize){
//        isLoopNetwork=false;
        myUDP.read(netPacket, packetSize);
        Serial.print((char)(netPacket[0]));
        Serial.println(" test_for_freeze");
    }
  }
//  isLoopNetwork=false;
}
```
I'm considering this issue closed for the time being.
